### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by AtulRajVAASITS** [HelpingAI/Helpingai_T2#2]
Traceback (most recent call last):
  File "d:\Working on\ml\research\test.py", line 966, in <module>
    for a in Perplexity().generate_answer(prompt):
             ^^^^^^^^^^^^
  File "d:\Working on\ml\research\research\Lib\site-packages\Helpingai_T2\Search.py", line 19, in __init__
    self.sid = loads(
               ^^^^^^
  File "C:\Users\alok.r\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alok.r\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alok.r\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Simatwa** [comment]
[This fork](https://github.com/Simatwa/Helpingai_T2) solves the issue. 

```sh
pip install Helpingai-T2-fork
```

**Comment by vihaanmody1** [comment]
I got the same error. I am using the fork version.
@Simatwa 
@Kritik-helpingai
